Hardhat allows external artifacts
ethereum-ts/TypeChain pull request #394
Opened 2021-06-02 11:08 UTC by ducquangkstn

Resolve https://github.com/ethereum-ts/TypeChain/issues/367

2021-06-07 18:48 UTC, krzkaczor requested changes
Thanks for working on it! Some comments.

2021-06-07 18:48 UTC, krzkaczor commented on packages/hardhat/src/index.ts
> +    const artifactsPaths = [`${config.paths.artifacts}/!(build-info)/**/+([a-zA-Z0-9_]).json`]
I think the better implementation would be to first run glob ignoring node_modules and later again to get external artifacts. Finally, merge both results. This way we don't modify old behaviour at all.

2021-06-07 18:48 UTC, krzkaczor commented on packages/hardhat/src/index.ts
> +    const needsFullRebuild =
Can we somehow support incremental generation with `externalArtifacts`? If I get it correctly we have no way of checking if we already generated types for externalArtifacts and this is the reason for this change. But maybe we can always generate typings only for `externalArtifacts` and avoid regenerating all types for internal files? Incremental generation is often a lifesaver.

2021-06-22 02:56 UTC, ducquangkstn commented
@krzkaczor can you review this PR again?

2021-06-23 11:28 UTC, krzkaczor approved these changes

2021-06-23 11:29 UTC, merged

2021-06-23 11:29 UTC, krzkaczor commented
Thanks! I will add changesets and try to release it soon.

2021-06-23 12:07 UTC, krzkaczor commented
Released as `@typechain/hardhat@2.1.0`